const { contextBridge, ipcRenderer } = require('electron');

const call = (channel) => (arg) => ipcRenderer.invoke(channel, arg);

contextBridge.exposeInMainWorld('api', {
  listUsers: call('users:list'),
  createUser: call('users:create'),
  login: call('users:login'),
  logout: call('users:logout'),
  createRemember: call('remember:create'),
  resumeRemember: call('remember:resume'),
  revokeRemember: call('remember:revoke'),
  listSubjects: call('subjects:list'),
  saveSubject: call('subjects:save'),
  deleteSubject: call('subjects:delete'),
  listSessions: call('sessions:list'),
  saveSession: call('sessions:save'),
  deleteSession: call('sessions:delete'),
  listNotes: call('notes:list'),
  saveNote: call('notes:save'),
  deleteNote: call('notes:delete'),
  spotifyStatus: call('spotify:status'),
  spotifySaveClientId: call('spotify:save-client-id'),
  spotifyConnect: call('spotify:connect'),
  spotifyDisconnect: call('spotify:disconnect'),
  spotifyState: call('spotify:state'),
  spotifyControl: call('spotify:control'),
  spotifyDevices: call('spotify:devices'),
  spotifyTransfer: call('spotify:transfer'),
  spotifyPlaylists: call('spotify:playlists'),
  spotifyPlayContext: call('spotify:play-context'),
  getActive: call('active:get'),
  saveActive: call('active:save'),
  clearActive: call('active:clear'),
});
